const USER_AGENT: &str = concat!(env!("CARGO_PKG_NAME"), "/", env!("CARGO_PKG_VERSION"));

pub mod bot;
pub mod config;
pub mod crates;
pub mod format;
pub mod fuzzy;
pub mod github;
pub mod helix;
pub mod help;
pub mod irc;
pub mod json;
pub mod logger;
pub mod manifest;
pub mod pattern;
pub mod rand;
pub mod re;
pub mod responder;
pub mod spotify;
pub mod store;
pub mod time;
pub mod watcher;
